USE cs105_asrivas;

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
	id INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	name VARCHAR(30), 
	password VARCHAR(30),
	fact1 VARCHAR(30),
	fact2 VARCHAR(30),
	fact3 VARCHAR(30) );

DROP TABLE IF EXISTS albums;

CREATE TABLE albums (
	album_id INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	album_name VARCHAR(30);
);

DROP TABLE IF EXISTS user_albums;

CREATE TABLE user_albums (
	id INT(5) NOT NULL REFERENCES users, 
	album_id INT(5) NOT NULL REFERENCES albums);
);

DROP TABLE IF EXISTS photos;

CREATE TABLE photos (
	photo_id INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(30);
	file VARCHAR(30);
);

DROP TABLE IF EXISTS album_photos;

CREATE TABLE album_photos (
	album_id INT(5) NOT NULL REFERENCES albums, 
	photo_id INT(5) NOT NULL REFERENCES photos);
);