<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html> 
  <head> 
    <title>Customer View</title>
    <meta charset="utf-8" />
  </head> 
  <body>
   <h1> Our Customers </h1><form method='post' action='add_customer.php'><h2>Name: </h2><input type='text' name='cname' value='Name'/><p>Address: </p><input type='text' name='street' value='Street'/><input type='text' name='zip' value='Zip'/><p>Phone #:</p> <input type='text' name='phone' value='Phone'/><input type='submit' name='add' value='Add Customer' /></form><form method='post' action='edit_customer.php'><h2>Name: CHARLES</h2><input type='hidden' name='cname' value='CHARLES'/><p>Address: 123 MAIN ST., </p><input type='hidden' name='street' value='123 MAIN ST.'/><input type='hidden' name='zip' value=''/><p>Phone #: 316-636-5555</p><input type='hidden' name='phone' value='316-636-5555'/><input type='hidden' name='cname' value='CHARLES'/><input type='hidden' name='cno' value=''/><input type='submit' name='edit' value='Edit' /><input type='submit' name='delete' value='Delete' /></form><form method='post' action='edit_customer.php'><h2>Name: BERTRAM</h2><input type='hidden' name='cname' value='BERTRAM'/><p>Address: 237 ASH AVENUE, </p><input type='hidden' name='street' value='237 ASH AVENUE'/><input type='hidden' name='zip' value=''/><p>Phone #: 316-689-5555</p><input type='hidden' name='phone' value='316-689-5555'/><input type='hidden' name='cname' value='BERTRAM'/><input type='hidden' name='cno' value=''/><input type='submit' name='edit' value='Edit' /><input type='submit' name='delete' value='Delete' /></form><form method='post' action='edit_customer.php'><h2>Name: BARBARA</h2><input type='hidden' name='cname' value='BARBARA'/><p>Address: 111 INWOOD ST., </p><input type='hidden' name='street' value='111 INWOOD ST.'/><input type='hidden' name='zip' value=''/><p>Phone #: 316-111-1234</p><input type='hidden' name='phone' value='316-111-1234'/><input type='hidden' name='cname' value='BARBARA'/><input type='hidden' name='cno' value=''/><input type='submit' name='edit' value='Edit' /><input type='submit' name='delete' value='Delete' /></form><form method='post' action='edit_customer.php'><h2>Name: Bendy</h2><input type='hidden' name='cname' value='Bendy'/><p>Address: CS Building utexas, </p><input type='hidden' name='street' value='CS Building utexas'/><input type='hidden' name='zip' value=''/><p>Phone #: 111-111-0000</p><input type='hidden' name='phone' value='111-111-0000'/><input type='hidden' name='cname' value='Bendy'/><input type='hidden' name='cno' value=''/><input type='submit' name='edit' value='Edit' /><input type='submit' name='delete' value='Delete' /></form> 
  </body>
</html>
